### ISSUE TITLE
1.6.3C - completely broken

### ISSUE THREAD

**Issue by dragonash2019** [Terri00/vrc8ball#79] opened 2021-03-09 03:46 UTC
This is in VRC. I've tested by removing the prefab completely and reinstalling from scratch with the same results
![VRChat_1920x1080_2021-03-08_22-34-57 277](https://user-images.githubusercontent.com/47508016/110415521-068c3600-8060-11eb-8de7-4bb08113a05f.png)

On a side note, I just noticed the "table refiner" addition.
Please do tell about it :)

**Comment by AbsolofDarkness** [comment] 2021-03-09 21:10
@dragonash2019 Try using the previous version of UdonSharp. I went back a version and it seemed to have worked. This may be an issue on their part and not on ht8b?

**Comment by dragonash2019** [comment] 2021-03-14 19:40
> @dragonash2019 Try using the previous version of UdonSharp. I went back a version and it seemed to have worked. This may be an issue on their part and not on ht8b?

Not thrilled with downgrading to a previous build. I'll keep the previous (I think it was B) until everything is sorted out. Looks like it was an incremental update by Harry.

**Comment by Ostinyo** [comment] 2021-03-17 06:42
I've been struggling with this as well. Been trying different combinations of ht8b & UdonSharp but nothing seems to work for me.

**Comment by Terri00** [comment] 2021-03-17 07:00
Really not sure whats causing it, I think im using latest udonsharp but not sure. will check tommorow. I had a slightly later build of 1.6.3c unity package on my pc so i've uploaded that (still sais released in the past on github). Would recommend try re-download it.

**Comment by Terri00** [comment] 2021-03-17 23:42
I can confirm that it's working with this configuration:

UdonSharp: v0.19.5
VRCSDK3: 2021.03.09.13.57
ht8b: 1.6.3c

Make sure to try full download/reinstall

**Closed by Terri00** 2021-03-17 23:42 UTC

**Comment by Ostinyo** [comment] 2021-03-18 00:09
Thanks for checking it out. I tried a new project with the latest VRCSDK & UdonSharp, then imported 1.6.4c and it still says YEET where all the text should be. Is there some dependency missing in the prefab?

**Comment by dragonash2019** [comment] 2021-03-18 00:38
Downloaded the "new" "c" package and made no changes to my U#. It is now working properly.

**Comment by Terri00** [comment] 2021-03-18 02:04
> 
> 
> Thanks for checking it out. I tried a new project with the latest VRCSDK & UdonSharp, then imported 1.6.4c and it still says YEET where all the text should be. Is there some dependency missing in the prefab?

It looks like that until you run the game, the button meshes get set when the scene starts

**Comment by Ostinyo** [comment] 2021-03-18 02:07
> > Thanks for checking it out. I tried a new project with the latest VRCSDK & UdonSharp, then imported 1.6.4c and it still says YEET where all the text should be. Is there some dependency missing in the prefab?
> 
> It looks like that until you run the game, the button meshes get set when the scene starts

Silly me, thanks!

**Comment by Terri00** [comment] 2021-03-18 02:13
I should make that more clear what its doing :P
