### ISSUE TITLE
Resize pool stick for small avatars + a collider for small avatars

### ISSUE THREAD

**Issue by Legoman99573** [Terri00/vrc8ball#55] opened 2021-01-23 04:31 UTC
Not sure if this is a high priority or not, but would be a good idea for small avatars that can't reach the table as the stick is too long and makes using it quite complicated. Not in a rush for it, but leaving as a suggestion.

**Comment by Terri00** [comment] 2021-01-23 11:49
Duplicate of #26 #28

**Closed by Terri00** 2021-01-23 11:49 UTC
