### ISSUE TITLE
Up down is inverted in desktop

### ISSUE THREAD

**Issue by kevinsaidjustanything** [Terri00/vrc8ball#95] opened 2021-04-23 15:01 UTC
Any fixes for this, I'm using the newest version of vrc8ball and udonsharp along with a 3.0 udon world. Everything works but for some reason the up down is inverted.

**Comment by kevinsaidjustanything** [comment] 2021-04-23 15:12
Created a new project, scene. Installed udon, udonsharp then 8ball same issue 
![explorer_nbXuAxWP_04-23-2021_10-09AM_fdm](https://user-images.githubusercontent.com/83081283/115892025-61b19680-a41c-11eb-96e5-7a153cdea3de.png)

**Comment by Terri00** [comment] 2021-04-23 16:56
Hiya, i'm not sure what causes it, but I would check out issue https://github.com/Terri00/vrc8ball/issues/94. they seem to have had a similar problem.

**Comment by Terri00** [comment] 2021-05-20 16:09
This issue was caused by 'vrlow' switching graphics api's from directx to opengl.

Fixed in next build by adding flip instructions to UI related shaders.

**Closed** 2021-05-23 23:20 UTC
Labels: done-next-build
