### ISSUE TITLE
Idea: Add a mirror on the map

### ISSUE THREAD

**Issue by grzegorz-dzikowski** [Terri00/vrc8ball#13] opened 2020-12-24 20:50 UTC
Really love the map and spends a lot of time with my crew in it. But sometimes, we need a mirror f.e. for calibration, avatar changing or photos. Could you add a toggable mirror somewhere on the map?

**Comment by Terri00** [comment] 2020-12-24 21:14
Duplicate of #12

**Closed by Terri00** 2020-12-24 21:14 UTC
